#!/bin/bash
yum update -y
yum install httpd -y
echo "<html><marquee><body><h1>This is DevOpsEval</h1></body></marquee></html>" > /var/www/html/index.html
service httpd start
chkconfig httpd on
wget -O /usr/bin/eval-server.linux-x86_64 https://github.com/PerformLine/DevOpsEval/blob/master/bin/eval-server.linux-x86_64
chmod 100 /usr/bin/eval-server.linux-x86_64
sh /usr/bin/eval-server.linux-x86_64
